# This is a basic workflow to help you get started with Actions

name: run-tests
run-name: ${{ github.actor }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zig: [ 0.16.0 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    name: Zig ${{ matrix.zig }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: ${{ matrix.zig }}
      - run: zig build test
